# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pupil_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(537, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(617, 700))
        Form.setStyleSheet("background-color: dodgerblue")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(-1, 10, -1, 11)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setStyleSheet("background-color: white; border-radius: 10px")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.pupil_name_line = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pupil_name_line.sizePolicy().hasHeightForWidth())
        self.pupil_name_line.setSizePolicy(sizePolicy)
        self.pupil_name_line.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pupil_name_line.setFont(font)
        self.pupil_name_line.setStyleSheet("border-radius: 5px;\n"
"background-color: white;\n"
"border: 2px solid black;\n"
"color: black;")
        self.pupil_name_line.setObjectName("pupil_name_line")
        self.horizontalLayout_2.addWidget(self.pupil_name_line)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, -1, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.pupil_class = QtWidgets.QLabel(self.widget_3)
        self.pupil_class.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pupil_class.setFont(font)
        self.pupil_class.setStyleSheet("border-radius: 5px;\n"
"background-color: white;\n"
"border: 2px solid black;\n"
"color: black;")
        self.pupil_class.setObjectName("pupil_class")
        self.horizontalLayout_6.addWidget(self.pupil_class)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.objects_box = QtWidgets.QComboBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objects_box.sizePolicy().hasHeightForWidth())
        self.objects_box.setSizePolicy(sizePolicy)
        self.objects_box.setMinimumSize(QtCore.QSize(250, 35))
        self.objects_box.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.objects_box.setFont(font)
        self.objects_box.setStyleSheet("QComboBox {\n"
"border-left: 2px solid black;\n"
"border-top: 2px solid black;\n"
"border-bottom: 2px solid black;\n"
"border-right: 2px solid black;\n"
"border-radius: 5px;\n"
"background-color: white;\n"
"color: black;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"   border-left: 2px solid black;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"   image: url(./static/arrow_down_1.png)\n"
"}")
        self.objects_box.setObjectName("objects_box")
        self.horizontalLayout_3.addWidget(self.objects_box)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.start_date = QtWidgets.QDateEdit(self.widget_3)
        self.start_date.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.start_date.setFont(font)
        self.start_date.setStyleSheet("QDateEdit {\n"
"border-left: 2px solid black;\n"
"border-top: 2px solid black;\n"
"border-right: 2px solid black;\n"
"border-bottom: 2px solid black;\n"
"border-radius: 5px;\n"
"background-color: white;\n"
"color: black;\n"
"font-color: black;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"   border-left: 2px solid black;\n"
"}\n"
"\n"
"QDateEdit::QCalendarWidget {\n"
"background-color: black;\n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"   image: url(./static/arrow_down_1.png)\n"
"}r")
        self.start_date.setCalendarPopup(True)
        self.start_date.setObjectName("start_date")
        self.horizontalLayout_4.addWidget(self.start_date)
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.finish_date = QtWidgets.QDateEdit(self.widget_3)
        self.finish_date.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.finish_date.setFont(font)
        self.finish_date.setStyleSheet("QDateEdit {\n"
"border-left: 2px solid black;\n"
"border-top: 2px solid black;\n"
"border-right: 2px solid black;\n"
"border-bottom: 2px solid black;\n"
"border-radius: 5px;\n"
"background-color: white;\n"
"color: black;\n"
"font-color: black;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"   border-left: 2px solid black;\n"
"}\n"
"\n"
"QDateEdit::QCalendarWidget {\n"
"background-color: black;\n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"   image: url(./static/arrow_down_1.png)\n"
"}r")
        self.finish_date.setCalendarPopup(True)
        self.finish_date.setObjectName("finish_date")
        self.horizontalLayout_4.addWidget(self.finish_date)
        self.month_ago = QtWidgets.QPushButton(self.widget_3)
        self.month_ago.setMinimumSize(QtCore.QSize(0, 35))
        self.month_ago.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.month_ago.setFont(font)
        self.month_ago.setStyleSheet("QPushButton {\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.month_ago.setObjectName("month_ago")
        self.horizontalLayout_4.addWidget(self.month_ago)
        self.month_later = QtWidgets.QPushButton(self.widget_3)
        self.month_later.setMinimumSize(QtCore.QSize(0, 35))
        self.month_later.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.month_later.setFont(font)
        self.month_later.setStyleSheet("QPushButton {\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.month_later.setObjectName("month_later")
        self.horizontalLayout_4.addWidget(self.month_later)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.average_score_line = QtWidgets.QLineEdit(self.widget_3)
        self.average_score_line.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.average_score_line.sizePolicy().hasHeightForWidth())
        self.average_score_line.setSizePolicy(sizePolicy)
        self.average_score_line.setMinimumSize(QtCore.QSize(0, 35))
        self.average_score_line.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.average_score_line.setFont(font)
        self.average_score_line.setStyleSheet("border-radius: 5px;\n"
"background-color: white;\n"
"border: 2px solid black;\n"
"color: black;")
        self.average_score_line.setObjectName("average_score_line")
        self.horizontalLayout_8.addWidget(self.average_score_line)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_9.setSpacing(7)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_2 = QtWidgets.QWidget(self.widget_3)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_9.addWidget(self.widget_2)
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.leaves_l = QtWidgets.QLineEdit(self.widget_3)
        self.leaves_l.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leaves_l.sizePolicy().hasHeightForWidth())
        self.leaves_l.setSizePolicy(sizePolicy)
        self.leaves_l.setMinimumSize(QtCore.QSize(55, 35))
        self.leaves_l.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.leaves_l.setFont(font)
        self.leaves_l.setStyleSheet("border-radius: 5px;\n"
"background-color: white;\n"
"border: 2px solid black;\n"
"color: black;")
        self.leaves_l.setObjectName("leaves_l")
        self.horizontalLayout_9.addWidget(self.leaves_l)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setStyleSheet("background-color: white; border-radius: 10px")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.graphics = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphics.sizePolicy().hasHeightForWidth())
        self.graphics.setSizePolicy(sizePolicy)
        self.graphics.setObjectName("graphics")
        self.verticalLayout_2.addWidget(self.graphics)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ФИО:"))
        self.pupil_name_line.setText(_translate("Form", "Имя"))
        self.label_4.setText(_translate("Form", "Класс:"))
        self.pupil_class.setText(_translate("Form", "Класс"))
        self.label_9.setText(_translate("Form", "Предмет:"))
        self.label_7.setText(_translate("Form", "С"))
        self.start_date.setDisplayFormat(_translate("Form", "dd-MM-yyyy"))
        self.label_8.setText(_translate("Form", "до"))
        self.finish_date.setDisplayFormat(_translate("Form", "dd-MM-yyyy"))
        self.month_ago.setText(_translate("Form", "ᐊᐊ"))
        self.month_later.setText(_translate("Form", "ᐅᐅ"))
        self.label_2.setText(_translate("Form", "Средний балл: "))
        self.label_5.setText(_translate("Form", "Количество пропусков:"))
        self.label_3.setText(_translate("Form", "График оценок ученика"))
        self.graphics.setText(_translate("Form", "TextLabel"))
